### ISSUE TITLE
First issue - hand gesture recognition

### ISSUE THREAD

**Issue by EmrNITK** [EmrNITK/GestureControl#2]
This issues explains how to raise future issues. Observe a few things:

- If your issue is a part of hand gesture recognition **add a milestone tag** (as added in this issue). Do not add any milestone for issues that address both parts of the project.
- **Add label of hand gesture** (and eye tracking if issues addresses both parts).
- Mention to whom you want to **assign the issue**.

This first issue will be assigned to all members in the hand gesture recognition team.

**Comment by Sanchit-sk** [comment]
Before moving ahead to implementing the solution for hand gesture media player control. Let's discuss a few ideas on how we can do this. Some of the ideas from my side:-

## Detecting convexity defects

#### Steps

1. Find the convex hull of the hand.
2. Count the number of convexity defects based on the number indicated by the fingers.
3. Take action accordingly.

#### Controls

✋ - play/ pause
✌🏻- volume up
👌 - forward
4️⃣ fingers - back

## Hand Motion Tracking

#### Steps

1. Creating a mask corresponding to the color of the user’s hand.
2. Tracking the centroid of the contour formed corresponding to the hand and noticing the direction of displacement.
3. Based on the directions, a particular control can be adjusted.

#### Controls

⬅️ - video back
➡️ - video forward
⬆️ - volume up
⬇️ - volume down
✋ - Play/ Pause
