### ISSUE TITLE
Testing installation

### ISSUE THREAD

**Issue by PK-cod3ch3mist** [EmrNITK/GestureControl#25]
In this issue all we have to do is to try installing the repo and running it on different platforms i.e. 
- Windows 11
- Windows 10
- macOS
- Linux

If anyone encounters any issues, mention it as a comment. If someone discovers a solution do the same.

**Comment by AmitSingh12345678** [comment]
In windows 10, it's working fine.

**Comment by PK-cod3ch3mist** [comment]
On macOS (Intel based) it should work fine.

On macOS (ARM based/M1), there are installation issues with mediapipe:
- Installation of mediapipe with pip is not possible (as far as I have seen).
- The alternate is to build mediapipe on the machine. 
   - This is a fairly simple process, but only works when running the terminal in Rosetta/Intel x86 mode (some more investigation required)
   - Also, I have yet to see the reason behind this, but as far as I know, it is because mediapipe does not support GPU acceleration which macOS tries to enforce.
   - The above process may take some time since it requires a stable internet.

If someone finds any alternate solution, do comment.

**Comment by Sanchit-sk** [comment]
> In windows 10, it's working fine.

Also in windows 11

**Comment by PK-cod3ch3mist** [comment]
> On macOS (Intel based) it should work fine.
> 
> On macOS (ARM based/M1), there are installation issues with mediapipe:
> - Installation of mediapipe with pip is not possible (as far as I have seen).
> - The alternate is to build mediapipe on the machine. 
>    - This is a fairly simple process, but only works when running the terminal in Rosetta/Intel x86 mode (some more investigation required)
>    - Also, I have yet to see the reason behind this, but as far as I know, it is because mediapipe does not support GPU acceleration which macOS tries to enforce.
>    - The above process may take some time since it requires a stable internet.
> 
> If someone finds any alternate solution, do comment.

Resolution full process:

Install the library mediapipe-silicon (this requires python 3.7 to 3.10 
`pip install mediapipe-silicon`

Then run the following command in terminal
`pip install --no-cache-dir opencv-contrib-python==4.5.5.64`

Rerun the script, it will ask for webcam and accessibility permissions, grant those.

In case script doesn't run change the OpenCV importing statement to the following -- `from cv2 import cv2`

**Comment by PK-cod3ch3mist** [comment]
Mediapipe-silicon is actually a third party (but credible) build of mediapipe for ARM 64 architecture.
